radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml
Add Remux Tier 03 to standard guide and SQP configs
=> Add Remux Tier 03

radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
Added the new MAX streaming service CF, and added dates to indicate when the config was last updated.
=> Added MAX and 'Updated' dates

sonarr/web-2160p-v4.yml
Reverts recyclarr/config-templates#3
=> Revert "Update web-2160p-v4.yml"

radarr/french-hd-bluray-web-multi.yml, radarr/french-hd-bluray-web-vostfr.yml, radarr/french-remux-web-1080p-multi.yml, radarr/french-remux-web-1080p-vostfr.yml, radarr/french-remux-web-2160p-multi.yml, radarr/french-remux-web-2160p-vostfr.yml, radarr/french-uhd-bluray-web-multi.yml, radarr/french-uhd-bluray-web-vostfr.yml, radarr/sqp/sqp-1-2160p.yml, sonarr/french-anime-multi-v4.yml, sonarr/french-anime-vostfr-v4.yml, sonarr/french-web-1080p-multi-v4.yml, sonarr/french-web-1080p-vostfr-v4.yml, sonarr/french-web-2160p-multi-v4.yml, sonarr/french-web-2160p-vostfr-v4.yml, sonarr/web-2160p-v4.yml, templates.json
- Added new SQP-1 (2160p) config
- Added SQP-1 (2160p) to templates json
- French configs maintenance release
=> New and Updated configs

radarr/french-hd-bluray-web-multi.yml, radarr/french-hd-bluray-web-vostfr.yml, radarr/french-uhd-bluray-web-multi.yml, radarr/french-uhd-bluray-web-vostfr.yml, radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml
- Added HD Bluray Tier 03
- Added CRiT Streaming Service
- Removed `Hybrid` from non-remux containing configs
=> Update to match latest guides changes

.github/workflows/yaml-lint.yml, .yamllint, radarr/french-hd-bluray-web-multi.yml, radarr/french-hd-bluray-web-vostfr.yml, radarr/french-remux-web-1080p-multi.yml, radarr/french-remux-web-1080p-vostfr.yml, radarr/french-remux-web-2160p-multi.yml, radarr/french-remux-web-2160p-vostfr.yml, radarr/french-uhd-bluray-web-multi.yml, radarr/french-uhd-bluray-web-vostfr.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/french-anime-multi-v4.yml, sonarr/french-anime-vostfr-v4.yml, sonarr/french-web-1080p-multi-v4.yml, sonarr/french-web-1080p-vostfr-v4.yml, sonarr/french-web-2160p-multi-v4.yml, sonarr/french-web-2160p-vostfr-v4.yml, sonarr/web-2160p-v4.yml
Also updated style in existing YAML files to address lint issues. The primary changes are:
- Word-wrap many comments to get it under the 100 character line length.
- Add vertical spacing (new lines) between commented sections for readability.
=> Add github workflow for YAML lint

radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
- update 'updated date' on recently updated config templates
=> Fix: Update 'Updated' dates

radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-4.yml, radarr/uhd-bluray-web.yml, sonarr/web-1080p-v4.yml
- Consistent application of line breaks between category blocks of CFs
=> Formatting consistency fixes

radarr/anime-radarr.yml, radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/anime-sonarr-v4.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
- Added OViD streaming service to Radarr & Sonarr
- Added ADN streaming service to Anime Sonarr
- Added WEB and Remux Tier 03 to Anime Radarr
- Added Remux tiers to Anime Sonarr
- Updated version dates, and added missing version dates
=> feat: Maintenance Update 2023-07-19

radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml
- Corrected updated dates for SQP config files
=> Fix: Corrected updated dates

radarr/sqp/sqp-1-2160p.yml
- Fixed incorrect line numbers for SQP-1 (2160p)
=> Line number fixes for SQP-1 (2160p)

radarr/sqp/sqp-1-1080p.yml, radarr/sqp/sqp-1-2160p.yml, templates.json
- Update audio scores in SQP-1 (1080p) and SQP-1 (2160p)
- Fix templates.json SQP-1 (1080p) entry
- Fix SQP-1 (1080p) header name
- Bump updated dates
=> Add new SQP-1 audio scores, small fixes

templates.json
- Fix to `sqp-1-1080p` template name
- Unhide templates as appropriate
=> Update Template Idientifiers

radarr/templates/anime-radarr.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, sonarr/templates/anime-sonarr-v4.yml
- Updated dates on modified templates
- Fixed header formatting
- Corrected DV (WEBDL) comments
=> Fix: Date updates, formatting and corrections

includes.json, radarr/includes/hd-bluray-web.yml, radarr/includes/sqp/sqp-2.yml, sonarr/includes/anime-sonarr-v4.yml, sonarr/includes/web-2160p-v4.yml
- Created four include templates based on a selection of guide profiles
- Removed user-choice scoring sections from includes
- Added these to the includes.json
=> First batch of includes

includes.json, radarr/includes/anime-radarr.yml, radarr/includes/remux-web-1080p.yml, radarr/includes/remux-web-2160p.yml, radarr/includes/sqp/sqp-1-1080p.yml, radarr/includes/sqp/sqp-1-2160p-4k-only-qp-default.yml, radarr/includes/sqp/sqp-1-2160p-4k-only-qp-prefer-imax-e.yml, radarr/includes/sqp/sqp-1-2160p-qp-default.yml, radarr/includes/sqp/sqp-1-2160p-qp-prefer-imax-e.yml, radarr/includes/sqp/sqp-1-2160p-shared.yml, radarr/includes/sqp/sqp-3.yml, radarr/includes/sqp/sqp-4.yml, radarr/includes/sqp/sqp-5.yml, radarr/includes/uhd-bluray-web.yml, sonarr/includes/web-1080p-v4.yml
- Created remaining profile includes
- Updated includes.json with new profile includes
NB - all includes only contain static options, *not* ones that are user-configurable (scores, etc). These will be added to the updated template files at a later date
=> Addition of remaining includes

radarr/includes/hd-bluray-web.yml
=> Do not reset score values in includes/hd-bluray-web.yml

radarr/includes/remux-web-1080p.yml, radarr/includes/remux-web-2160p.yml, radarr/includes/uhd-bluray-web.yml
- Remove score lines which were setting all include CFs to be scored at 0
=> Fix zero scoring includes

radarr/templates/remux-web-2160p.yml, radarr/templates/uhd-bluray-web.yml, sonarr/templates/web-1080p-v4.yml, sonarr/templates/web-2160p-v4.yml
- Corrected incorrect month on config templates
=> Fix template dates

radarr/includes/anime-radarr.yml, radarr/includes/hd-bluray-web.yml, radarr/includes/remux-web-1080p.yml, radarr/includes/remux-web-2160p.yml, radarr/includes/sqp/sqp-1-1080p.yml, radarr/includes/sqp/sqp-1-2160p-shared.yml, radarr/includes/sqp/sqp-2.yml, radarr/includes/sqp/sqp-3.yml, radarr/includes/sqp/sqp-4.yml, radarr/includes/sqp/sqp-5.yml, radarr/includes/uhd-bluray-web.yml, radarr/templates/anime-radarr.yml, radarr/templates/remux-web-1080p.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-1080p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml, sonarr/includes/anime-sonarr-v4.yml, sonarr/includes/web-1080p-v4.yml, sonarr/includes/web-2160p-v4.yml, sonarr/templates/anime-sonarr-v4.yml, sonarr/templates/web-2160p-v4.yml
- Added `Extras` to SQP-1 Include
- Formatting changes for all comments (happy cactus noises)
=> fix: SQP-1 Update and Formatting Changes

radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml
- Add UHD Bluray Tiers to SQP-1 (2160p)
=> feat: SQP-1 (2160p) Update

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Added new LQ (Release Title) CF to Radarr and Sonarr profiles
- Added new FOD, TVer and U-NEXT streaming service CFs to Radarr and Sonarr profiles
- Added new 4OD and ALL4 streaming service CFs to Sonarr profiles
=> feat: Add LQ (Release Title) and Streaming Service CFs

sonarr/includes/custom-formats/sonarr-v4-custom-formats-anime.yml
- Add ABEMA streaming service to Sonarr Anime
=> feat: Add ABEMA Streaming Service

radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Update includes with new DV HDR10Plus custom format
=> feat: Add DV HDR10 Plus Custom Format

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/templates/hd-bluray-web.yml, radarr/templates/remux-web-1080p.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-1080p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml, sonarr/templates/web-1080p-v4.yml, sonarr/templates/web-2160p-v4.yml
- Add optional custom formats to Sonarr templates
- Update Radarr optional custom formats to match guides
- Update SQP optional custom formats to match guides
- Add configuration to all templates for switching between `x265 (HD)` and `x265 (no HDR/DV)` custom formats as appropriate
- Added `Upscaled` custom format to Radarr includes
- Amended custom format comments with updated custom format names
- Updated template dates
=> feat: Update Template Optionals and Other Maintenance

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Add iPlayer streaming service custom format to all includes
=> feat: Add iPlayer Streaming Service

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Add HTSR streaming service to all relevant template includes
=> feat: Add Disney+ Hotstar (HTSR) Streaming Service

radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Sort Streaming Service Custom Formats Alphabetically
=> chore: Sort Streaming Service Custom Formats Alphabetically

sonarr/includes/custom-formats/sonarr-v4-custom-formats-anime-fr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-anime-vostfr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p-fr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p-multi-fr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p-vostfr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p-fr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p-multi-fr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p-vostfr.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-anime-fr.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-anime-vostfr.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-web-1080p-fr.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-web-1080p-vostfr.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-web-2160p-fr.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-web-2160p-vostfr.yml, sonarr/templates/french-anime-multi-v4.yml, sonarr/templates/french-anime-vostfr-v4.yml, sonarr/templates/french-web-1080p-multi-v4.yml, sonarr/templates/french-web-1080p-vostfr-v4.yml, sonarr/templates/french-web-2160p-multi-v4.yml, sonarr/templates/french-web-2160p-vostfr-v4.yml
- Anime (MULTi & VOSTFR)
- Web 1080p (MULTi & VOSTFR)
- Web 2160p (MULTi & VOSTFR)
- Created Includes for all FR profiles
- Updated the templates with latest changes
[Upcoming]
- Will do another PR later this week with the Radarr ones
=> feat: Update Sonarr French Recyclarr templates

includes.json
- Recently added French includes were not added to the include library, so were not available in the app.
=> fix: Add French includes to include library

sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Remove remaining non-general streaming services from Sonarr custom format includes
=> fix: Remove remaining non-general streaming services

.gitignore, radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml
- Add new Repack3 custom format to Radarr includes
=> feat: Add new Repack3 custom format to Radarr includes

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, radarr/templates/sqp/sqp-1-2160p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
- Move the AV1 custom format to the unwanted section in all profiles.
=> feat: Move AV1 to unwanted

includes.json, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-web-1080p.yml, radarr/includes/quality-profiles/sqp/radarr-quality-profile-sqp-1-web-1080p.yml, radarr/templates/sqp/sqp-1-web-1080p.yml, templates.json
- Add hallowed to SQP-1 (1080p) and SQP-1 (2160p) profiles
- Create template and includes for new SQP-1 WEB (1080p) profile
- Add new SQP-1 WEB (1080p) template and includes to dictionary JSONs
=> feat: SQP-1 Updates

radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-web-1080p.yml
- Fixed incorrect quality profile name on SQP-1 WEB (1080p) custom formats include
=> fix: Fixed incorrect quality profile name on SQP-1 WEB (1080p) custom formats include

includes.json
=> fix: update includes.json with new French include files

radarr/templates/french-hd-bluray-web.yml, radarr/templates/french-hd-remux-web.yml, radarr/templates/french-uhd-bluray-web.yml, radarr/templates/french-uhd-remux-web.yml
=> Fix: update French Radarr templates

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-web-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml
- Add Generated Dynamic HDR custom format to Unwated section of all main-guide includes
=> feat: Add Generated Dynamic HDR custom format

radarr/templates/german-hd-bluray-web.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml, templates.json
Added the 3 top level templates for the German Guide
=> feat: added top level templates for the German Guide

radarr/templates/german-hd-bluray-web.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml
Fixed the minimum custom format score to be 0.
=> Fix: updated German templates minimum score to 0

includes.json, sonarr/includes/custom-formats/sonarr-v4-custom-formats-hd-bluray-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-hd-remux-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-uhd-bluray-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-uhd-remux-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-hd-bluray-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-hd-remux-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-uhd-bluray-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-uhd-remux-web-german.yml, sonarr/templates/german-hd-bluray-web.yml, sonarr/templates/german-hd-remux-web.yml, sonarr/templates/german-uhd-bluray-web.yml, sonarr/templates/german-uhd-remux-web.yml, templates.json
Adding top-level templates and includes for the German Sonarr Guide.
=> Feat: add templates for the German Sonarr Guide

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-web-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, radarr/templates/hd-bluray-web.yml, radarr/templates/remux-web-1080p.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-1080p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-1-web-1080p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml
Add Black and White Versions (optional) and Sing-Along Versions (unwanted) custom formats to all main guide profiles and includes
=> feat: Add Black and White Versions and Sing-Along Versions custom formats

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-remux-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-hd-bluray-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-hd-remux-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-uhd-bluray-web-german.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-uhd-remux-web-german.yml
* add German LQ (Release Title) CF to includes
=> feat: Add German LQ (Release Title) CF to includes

includes.json, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-web-2160p.yml, radarr/includes/quality-profiles/sqp/radarr-quality-profile-sqp-1-web-2160p-4k-only.yml, radarr/includes/quality-profiles/sqp/radarr-quality-profile-sqp-1-web-2160p.yml, radarr/templates/sqp/sqp-1-web-2160p.yml, templates.json
Add SQP-1 WEB (2160p) template and related files
=> feat: Add SQP-1 WEB (2160p) template and related files

sonarr/includes/custom-formats/sonarr-v4-custom-formats-bluray-web-2160p-french-multi-vf.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-bluray-web-2160p-french-multi-vo.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-bluray-web-2160p-french-vostfr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml
=> feat: Replace UHD Streaming Cut custom format with HD Streaming Boost
