radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
- Added Crave (CRAV) streaming service to Main Guide and SQP configs for Radarr/Sonarr
=> Feat add Crave streaming service

sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
- Relocate CRAV for Sonarr configs to the streaming service CF block, now that CRAV has a default guide score
=> Relocate CRAV (Sonarr configs)

radarr/sqp/sqp-2.yml, radarr/sqp/sqp-5.yml
- Make UHD Bluray Tier Scores explicit for SQP2 + SQP5, to support an upcoming change to the default scores of these custom formats
=> fix(radarr): Specify UHD Bluray Tier Scores

radarr/anime-radarr.yml, radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-1080p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/anime-sonarr-v4.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
- Renamed SQP-1 to SQP-1 (1080p) in all areas
- Renamed SQP-1 (1080p) and SQP-1 (2160p) quality profiles to SQP-1 (1080p) and SQP-1 (2160p) (i.e., no longer Bluray|WEB-1080p etc.)
- Updated SQP-1 (1080p) and SQP-1 (2160p) config templates to match updated guides
- Reformatted SQP-1 (1080p) and SQP-1 (2160p) config templates to match guide layout (i.e., no longer split by standard/custom scoring)
- Updated all config templates to use an instance name that matches the name of the template
- Updated base_url and api_key fields to be consistent across all config templates
=> Maintenance Release 01/08/2023

radarr/anime-radarr.yml, radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-1080p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-1.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/anime-sonarr-v4.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
- Removed array/sequence syntax from base_url and api_key placeholders.
=> Fix: Removed array/sequence syntax from base_url and api_key placeholders.

radarr/sqp/sqp-1-2160p.yml
- Make x265 (no HDR/DV) the default golden rule option
- Applied consistent spacing to CF blocks
- Removed unnecessary empty lines
=> Fix(SQP-1-2160p): Correct default golden rule usage, and apply .yml tidying

radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml
- relocated `quality_profiles` block to ensure Optional CFs remain functional for SQP-2 through SQP-5
- Fixes to line numbers and ordering for SQP-1 (2160p)
- Uncommenting recommended CFs for SQP-1 (2160p)
=> Fixes to SQP config files

radarr/anime-radarr.yml, radarr/french-hd-bluray-web-multi.yml, radarr/french-hd-bluray-web-vostfr.yml, radarr/french-remux-web-1080p-multi.yml, radarr/french-remux-web-1080p-vostfr.yml, radarr/french-remux-web-2160p-multi.yml, radarr/french-remux-web-2160p-vostfr.yml, radarr/french-uhd-bluray-web-multi.yml, radarr/french-uhd-bluray-web-vostfr.yml, radarr/hd-bluray-web.yml, radarr/remux-web-1080p.yml, radarr/remux-web-2160p.yml, radarr/sqp/sqp-1-1080p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml, radarr/uhd-bluray-web.yml, sonarr/anime-sonarr-v4.yml, sonarr/french-anime-multi-v4.yml, sonarr/french-anime-vostfr-v4.yml, sonarr/french-web-1080p-multi-v4.yml, sonarr/french-web-1080p-vostfr-v4.yml, sonarr/french-web-2160p-multi-v4.yml, sonarr/french-web-2160p-vostfr-v4.yml, sonarr/web-1080p-v4.yml, sonarr/web-2160p-v4.yml
This new syntax was introduced in v5.3.0. See deprecation notice here: https://recyclarr.dev/wiki/upgrade-guide/v6.0/#reset-scores
=> Use new reset_unmatched_scores syntax

radarr/sqp/sqp-1-1080p.yml, radarr/sqp/sqp-1-2160p.yml, radarr/sqp/sqp-2.yml, radarr/sqp/sqp-3.yml, radarr/sqp/sqp-4.yml, radarr/sqp/sqp-5.yml
- Add `score_sets` variable to SQP config files
- Remove manual custom scores from SQP config files
=> Feature: Add Score Sets to SQP config files

radarr/templates/anime-radarr.yml, sonarr/templates/anime-sonarr-v4.yml
Updated to include `score_set` flag introduced in latest version of recyclarr.
Combined trash_id's in line with how a score_set is handled.
Cleaned up Adjustable section to be in line with the originating guide.
=> chore: :wrench: Update for score_set flag

radarr/templates/french-hd-bluray-web-multi.yml, radarr/templates/french-hd-bluray-web-vostfr.yml, radarr/templates/french-remux-web-1080p-multi.yml, radarr/templates/french-remux-web-1080p-vostfr.yml, radarr/templates/french-remux-web-2160p-multi.yml, radarr/templates/french-remux-web-2160p-vostfr.yml, radarr/templates/french-uhd-bluray-web-multi.yml, radarr/templates/french-uhd-bluray-web-vostfr.yml
Update all 8 French Radarr Recyclarr template configuration files to latest development.
=> fix(french-radarr): update recyclarr configs

includes.json
anime-radarr was missing from [includes.json](https://github.com/recyclarr/config-templates/blob/master/includes.json) which throws an unable to find template error.
=> Add anime-radarr to includes.json

radarr/templates/anime-radarr.yml
Moved 10bit to manually defined scoring section to avoid "no scores assigned" error message
=> fix(anime-radarr): manually set 10bit scoring to 0

radarr/includes/sqp/sqp-2.yml, radarr/includes/sqp/sqp-3.yml, radarr/includes/sqp/sqp-4.yml, radarr/includes/sqp/sqp-5.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml
- relocate golden rule choice, and DV (FEL) and SDR optionals to the templates instead of the include
=> Move SQP 2-5 Optionals

radarr/includes/hd-bluray-web.yml, radarr/includes/remux-web-1080p.yml, radarr/includes/remux-web-2160p.yml, radarr/includes/sqp/sqp-1-2160p-shared.yml, radarr/includes/uhd-bluray-web.yml, radarr/templates/anime-radarr.yml, radarr/templates/hd-bluray-web.yml, radarr/templates/remux-web-1080p.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-1080p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/uhd-bluray-web.yml, sonarr/includes/web-2160p-v4.yml, sonarr/templates/anime-sonarr-v4.yml, sonarr/templates/web-1080p-v4.yml, sonarr/templates/web-2160p-v4.yml
- Update templates to enable `custom_formats` section by default, as Recyclarr now supports empty sections
- Move `SDR` optional out of all includes and into templates
- Add `Extras` CF to all includes
=> feat: Simplify Templates, Update Includes and Relocate Optionals

radarr/includes/remux-web-2160p.yml, radarr/includes/sqp/sqp-1-2160p-shared.yml, radarr/includes/sqp/sqp-2.yml, radarr/includes/sqp/sqp-3.yml, radarr/includes/sqp/sqp-4.yml, radarr/includes/sqp/sqp-5.yml, radarr/includes/uhd-bluray-web.yml, radarr/templates/hd-bluray-web.yml, radarr/templates/remux-web-1080p.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-1080p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml, sonarr/includes/web-2160p-v4.yml, sonarr/templates/web-2160p-v4.yml
- Re-added all recommended optional custom formats to main guide and SQP includes
- Revised 'Golden Rule' defaults for all profiles so they match the guide recommendations
- Added revised sections to main guide and SQP templates to allow users to override recommended optional custom format scores
- Recategorised custom format groupings to use the same header names as the guides
- Updated file modification dates
Users will need to update their templates
=> feat: Optional Custom Formats Reconciliation

radarr/includes/quality-profiles/radarr-quality-profile-anime.yml
- Add Bluray-576p quality to Radarr Anime quality profile include
=> Fix: Add Bluray-576p Quality to Radarr Anime Quality Profile Include

includes.json
- Remove legacy includes from includes.json, so that `recyclarr config list templates -i` does not erroneously show these as available.
=> fix: Fully Remove Legacy Includes

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, radarr/templates/french-hd-bluray-web-multi.yml, radarr/templates/french-hd-bluray-web-vostfr.yml, radarr/templates/french-remux-web-1080p-multi.yml, radarr/templates/french-remux-web-1080p-vostfr.yml, radarr/templates/french-remux-web-2160p-multi.yml, radarr/templates/french-remux-web-2160p-vostfr.yml, radarr/templates/french-uhd-bluray-web-multi.yml, radarr/templates/french-uhd-bluray-web-vostfr.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml, sonarr/templates/french-web-1080p-multi-v4.yml, sonarr/templates/french-web-1080p-vostfr-v4.yml, sonarr/templates/french-web-2160p-multi-v4.yml, sonarr/templates/french-web-2160p-vostfr-v4.yml
- Revert all includes and French templates to use previous combined `Repack/Proper` custom format
=> fix: Revert Repack/Proper Custom Format Changes

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml, sonarr/templates/web-2160p-v4.yml
- Added ITVX and VIU streaming services to Sonarr and Radarr custom format includes
- Added Hi10P to SQP-1 custom format includes as unwanted
- Added DV HDR10+ Boost to 4K optional section in all templates
- Reformatted HDR10+ section in all templates for consistency
=> feat: Add Streaming Services and DV HDR10+ Boost Option

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-1080p.yml, radarr/includes/custom-formats/radarr-custom-formats-remux-web-2160p.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-1080p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-2.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-3.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-4.yml, radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-5.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-1080p.yml, sonarr/includes/custom-formats/sonarr-v4-custom-formats-web-2160p.yml, sonarr/templates/web-2160p-v4.yml
- Brought the templates and includes up to date with the guides as of 2024-05-21
- Moved SDR custom formats out of includes and into templates
- Removed non-general streaming services
Notes for users:
- Non-general streaming services will now need to be manually added to your templates
- All users will need to update their templates to the latest version(s)
=> feat: Template Updates 2024-05-21

includes.json, radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-remux-web-german.yml
Added three templates based on the international ones for the CFs for the German Guide.
=> feat: Add custom format includes for the German Guide

includes.json, radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web-german-alternative.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-remux-web-german.yml, radarr/templates/german-hd-bluray-web.yml, radarr/templates/german-uhd-bluray-web-alternative.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml, templates.json
We want the templates to be 100% in sync with the written guide, so we adapted the templates for the german guide to achieve this.
=> fix: adapt templates for german guide to fully cover the written guide

includes.json
There was a typo in the include file at the IDs of the german quality profiles.
=> fix: German Guide templates - typo in includes.json

includes.json
Another typo, fixing problems while at work with other things is not a good idea :(
=> fix: German Guide templates - another typo in the include.json

radarr/templates/german-hd-bluray-web.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml
The UHD and Remux top level templates were wrongly referencing the HD quality profiles.
=> Fix: German Guide templates - wrong reference in top level templates

radarr/includes/custom-formats/radarr-custom-formats-hd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-bluray-web-german.yml, radarr/includes/custom-formats/radarr-custom-formats-uhd-remux-web-german.yml, radarr/includes/quality-profiles/radarr-quality-profile-hd-bluray-web-german.yml, radarr/includes/quality-profiles/radarr-quality-profile-uhd-bluray-web-german.yml, radarr/includes/quality-profiles/radarr-quality-profile-uhd-remux-web-german.yml, radarr/templates/german-hd-bluray-web.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml
- Add the not english or german CF to the profiles.
- Adapt the maximum score to be more than the actual maximum score, increase penalties in profiles for blockers to reflect that (penalties in the CFs itself will be adjusted for the german guide soon as well)
- Set the german score_set to always take the german scores.
=> Fix: add not english or german CF, maximum score adjustments and introduce the german score_set for the german radarr profiles 

includes.json
The reference to the template for the uhd-Bluray-web-German was duplicate and the uhd-Remux-web-German was missing
=> fix: german sonarr templates - duplicate reference in includes.json

sonarr/templates/german-hd-bluray-web-v4.yml, sonarr/templates/german-hd-remux-web-v4.yml, sonarr/templates/german-uhd-bluray-web-v4.yml, sonarr/templates/german-uhd-remux-web-v4.yml, templates.json
As apparently when using `recyclarr config create -t` the command only looks at the name of the template - the templates names across sonarr and radarr should be unique.
Thats why we updated the sonarr template names.
=> fix: make sonarr template names unique for the german guide

radarr/includes/quality-profiles/radarr-quality-profile-hd-bluray-web-german.yml, radarr/includes/quality-profiles/radarr-quality-profile-uhd-bluray-web-german.yml, radarr/includes/quality-profiles/radarr-quality-profile-uhd-remux-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-hd-bluray-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-hd-remux-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-uhd-bluray-web-german.yml, sonarr/includes/quality-profiles/sonarr-v4-quality-profile-uhd-remux-web-german.yml
reset unmatched scores should be true in the german guide as it is in the other guides templates
=> Fix: reset unmatched scores should be true in the german guide templates

radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml
Removed duplicate AV1 custom format from SQP-1 (2160p) include
=> fix: Removed duplicate AV1 custom format from SQP-1 (2160p) include

radarr/templates/french-hd-bluray-web.yml, radarr/templates/french-hd-remux-web.yml, radarr/templates/french-uhd-bluray-web.yml, radarr/templates/french-uhd-remux-web.yml, radarr/templates/german-hd-bluray-web.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml, radarr/templates/hd-bluray-web.yml, radarr/templates/remux-web-1080p.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-1-1080p.yml, radarr/templates/sqp/sqp-1-2160p.yml, radarr/templates/sqp/sqp-1-web-1080p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml
- Removed `EVO (no WEBDL)` custom format from all templates
=> fix: Resolve errors resulting from downstream `EVO (no WEBDL)` custom format removal

radarr/templates/anime-radarr.yml
The `movie` quality definitions were being used in the anime template. This has now been switched to correctly use the `anime` quality definitions.
=> fix: Incorrect quality definitions used in anime Radarr template

radarr/includes/custom-formats/sqp/radarr-custom-formats-sqp-1-2160p.yml, radarr/templates/french-uhd-bluray-web.yml, radarr/templates/french-uhd-remux-web.yml, radarr/templates/german-uhd-bluray-web.yml, radarr/templates/german-uhd-remux-web.yml, radarr/templates/remux-web-2160p.yml, radarr/templates/sqp/sqp-2.yml, radarr/templates/sqp/sqp-3.yml, radarr/templates/sqp/sqp-4.yml, radarr/templates/sqp/sqp-5.yml, radarr/templates/uhd-bluray-web.yml, sonarr/templates/french-bluray-web-2160p-v4.yml, sonarr/templates/german-uhd-bluray-web-v4.yml, sonarr/templates/german-uhd-remux-web-v4.yml, sonarr/templates/web-2160p-v4.yml
- Replaced all instances of `DV (WEBDL)` with `DV w/o HDR (WEBDL)`
- This applies consistency with an upcoming Guides change
=> chore: change `DV (WEBDL)` name to `DV w/o HDR (WEBDL)`

radarr/templates/sqp/sqp-1-web-2160p.yml
- One optional block in the new SQP-1 WEB 2160p was using the incorrect profile name. This has been corrected.
- Users will need to update their templates.
=> fix: SQP-1-WEB-2160p custom format assignation in optional template block
